# FP16 Performance Test Configuration

global:
  exporters:
    e1:
      format: "text"
      to: "stdout"
    e2:
      format: "json"
      to: "file://tmp/github-perf.json"


NYTimes-fp16:
    datapath: "/tmp/data/nytimes-256-angular.hdf5"
    type: "build,search"
    index_name: "hgraph"
    create_params: '{"dim":256,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"fp16","max_degree":80,"ef_construction":300}}'
    search_params: '{"hgraph":{"ef_search":132}}'
    index_path: "/tmp/nytimes-256-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true
